codigo/pcc/ONG/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('cadastro/', views.Cadastro, name='Cadastro'),
    path('editar/', views.Editar, name='Editar'),
    path('listar/', views.Listar, name='Listar'),
    path('detalhar/<id_ong>', views.Detalhar, name='Detalhar'),
    path('meu-perfil/', views.MeuPerfil, name='MeuPerfil')
]

codigo/pcc/pcc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('user.urls')),
    path('', include('user.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
    path('ong/', include('ONG.urls')),
    path('usuario/', include('usuario.urls')),
    path('animais/', include('animal.urls'))
]

codigo/pcc/usuario/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('cadastro/', views.Cadastro, name='Cadastro'),
    path('editar/', views.Editar, name='Editar'),
    path('listar/', views.Listar, name='Listar'),
    path('meu-perfil/', views.MeuPerfil, name='MeuPerfil')
]

codigo/pcc/user/models.py
from django.db import models
from django.contrib.auth.models import User
from django.contrib.auth.models import AbstractUser
from django.core import validators
from django.utils import timezone
import re
from .managers import CustomUserManager
from django.contrib.auth.models import PermissionsMixin

# Create your models here.
class Usuario(AbstractUser, PermissionsMixin):
    username = models.CharField(('username'), max_length=15, unique=True, help_text=('Required. 15 characters or fewer. Letters, numbers and @/./+/-/_ characters'), validators=[ validators.RegexValidator(re.compile('^[\w.@+-]+$'), ('Enter a valid username.'), ('invalid'))])
    first_name = models.CharField(('first name'), max_length=30)
    last_name = models.CharField(('last name'), max_length=30)
    email = models.EmailField(('email address'), max_length=255, unique=True)
    is_staff = models.BooleanField(('staff status'), default=False, help_text=('Designates whether the user can log into this admin site.'))
    is_active = models.BooleanField(('active'), default=True, help_text=('Designates whether this user should be treated as active. Unselect this instead of deleting accounts.'))
    date_joined = models.DateTimeField(('date joined'), default=timezone.now)
    is_superuser = models.BooleanField(('active'), default=False)
    choose_ong = models.BooleanField(('ong'), default=False)

    telefone = models.CharField(max_length=15, blank=False, null=True)
    imagem = models.ImageField(upload_to='static/imagens/perfil/', null=True, blank=True)

    USERNAME_FIELD = 'username'
    REQUIRED_FIELDS = ['email']

    objects = CustomUserManager()

   

codigo/pcc/usuario/models.py
from django.db import models
from django.contrib.auth import get_user_model


class Usuario(models.Model):
    email = models.EmailField(max_length = 256, blank=False, null=True)
    nome = models.CharField(max_length = 100, blank=False, null=True)
    sobrenome = models.CharField(max_length=100, blank=False, null=True)
    telefone = models.CharField(max_length=15, blank=False, null=True)
    user = models.OneToOneField(get_user_model(), on_delete=models.CASCADE)
    imagem = models.ImageField(upload_to='static/imagens/perfil/', null=True, blank=True)


codigo/pcc/usuario/forms.py
from django import forms 
from .models import Usuario

class AdicionarUsuario(forms.ModelForm):
    class Meta:
        model= Usuario
        fields = ('nome', 'sobrenome', 'email','telefone', 'imagem')

codigo/pcc/usuario/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import AdicionarUsuario 
from .models import Usuario
import os

@login_required
def Cadastro (request):
    if request.method =='POST':
        form = AdicionarUsuario(request.POST, request.FILES)
        if form.is_valid():
            a = form.save(commit=False)
            a.user = request.user
            a.save()
            return redirect('/accounts/')
    else:
        form = AdicionarUsuario()
    
    return render(request, 'Usuario/Cadastro.html', {'form': form})

@login_required
def Editar(request):
    u = request.user
    usuario= get_object_or_404(Usuario, user=u)
    form = AdicionarUsuario(instance=usuario)
    if request.method == 'POST':
        form = AdicionarUsuario(request.POST, request.FILES, instance=usuario)

        requisicao = request.POST.get('imagem', False)
        if requisicao:
            if len(usuario.imagem)>0:
                os.remove(usuario.imagem.path)
            usuario.imagem = request.FILES['imagem']

        if form.is_valid():
            form.save()
            return redirect('/accounts/')
        else:
            return render(request, 'Usuario/Editar.html', {'form': form, 'usuario': usuario})   
    
    else:
        return render(request, 'Usuario/Editar.html', {'form': form, 'usuario': usuario})

@login_required
def Listar(request):
    usuarios = Usuario.objects.all()
    return render(request, 'Usuario/Listar.html', {'usuarios': usuarios})

@login_required
def MeuPerfil(request):
    u = request.user
    usuario = Usuario.objects.get(user=u)
    return render(request, 'Usuario/Detalhar.html', {'usuario': usuario})

codigo/pcc/templates/Usuario/Cadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>AdotaPet</title>

    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">

    <!-- Styles -->
    <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body style="background-color: rgb(250, 208, 203);">
    <div class="unix-login">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="login-content">
                        <div class="login-form">
                            <h4>Cadastro</h4>
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="id_nome">Nome </label>
                                    <input type="text" class="form-control" placeholder="Nome" name="nome" maxlength="100" required id="id_nome">
                                </div>
                                <div class="form-group">
                                    <label for="id_sobrenome">Sobrenome</label>
                                    <input class="form-control" placeholder="Sobrenome"  type="text" name="sobrenome" maxlength="100" required id="id_sobrenome">
                                </div>
                                <div class="form-group">
                                    <label for="id_email">Email</label>
                                    <input class="form-control" placeholder="Email" type="email" name="email" maxlength="256" required id="id_email">
                                </div>
                                <div class="form-group">
                                    <label for="id_telefone">Telefone</label>
                                    <input class="form-control" placeholder="Telefone" type="text" name="telefone" maxlength="15" required id="id_telefone">
                                </div>
                                <div class="form-group">
                                    <label for="id_telefone">Selecione uma imagem de perfil</label>
                                    <input type="file" class="form-control" id="id_imagem" name="imagem">
                                </div>
                                <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30" style="background-color: rgb(233, 110, 96);">Cadastrar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

codigo/pcc/templates/Usuario/Detalhar.html

{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- theme meta -->
    <meta name="theme-name" content="focus" />
    <title>AdotaPet</title>
    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">
    <!-- Styles -->
    <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/chartist/chartist.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/owl.carousel.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/lib/owl.theme.default.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/lib/menubar/sidebar.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body  style="background-color: rgb(253, 237, 232);">

    <!-- /# sidebar -->

    <div class="header" style="margin-left:0px">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="float-left">
                        <div class="header-icon" >
                            <span class="user-avatar">
                                <a href="/animais/listar/" class="btn-outline btn btn-link"><i class="ti-angle-double-left"></i></a> 
                            </span>
                        </div>
                    </div>
                    <div class="float-right">
                        <div class="header-icon" >
                            <span class="user-avatar">
                                <a href="/accounts/meu-perfil/" class="btn-outline btn btn-link"><i class="ti-settings"></i></a> 
                            </span>
                            <span class="user-avatar"> 
                                <a href="/accounts/logout/" class="btn-outline btn btn-link " name='Sair'><i class="ti-shift-right"></i></a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="content-wrap">
        <div class="main">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-4 col-xl-3">
                        <div class="card">
                            <div class="card-body">
                                <div class="media align-items-center mb-4">
                                    <img class="mr-3" src="/{{u.imagem}}" width="60" height="60" alt="">
                                </div>
                            </div>
                        </div>  
                    </div>
                    <div class="col-lg-8 col-xl-9">
                        <div class="card">
                            <div class="card-body">
                                <div class="media-body">
                                    <h3 class="mb-0">{{u.nome}} {{u.sobrenome}}</h3>
                                </div>
                                <p>Email: {{u.email}}</p>
                                <p>Telefone: {{u.telefone}}</p>
                                <a class="btn btn-secondary px-3 ml-4" href='/accounts/editar/'>Editar</a>
                                <a class="btn btn-secondary px-3 ml-4" href='/accounts/password_change/'>Mudar senha</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /# row -->
            </div>
        </div>
    </div>

    <!-- jquery vendor -->
    <script src="{% static 'js/lib/jquery.min.js' %}"></script>
    <script src="{% static 'js/lib/jquery.nanoscroller.min.js' %}"></script>
    <!-- nano scroller -->
    <script src="{% static 'js/lib/menubar/sidebar.js' %}"></script>
    <script src="{% static 'js/lib/preloader/pace.min.js' %}"></script>
    <!-- sidebar -->

    <script src="{% static 'js/lib/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <!-- bootstrap -->


    <script src="{% static 'js/lib/chartist/chartist.min.js' %}"></script>
    <script src="{% static 'js/lib/sparklinechart/jquery.sparkline.min.js' %}"></script>
    <script src="{% static 'js/lib/sparklinechart/sparkline.init.js' %}"></script>
    <script src="{% static 'js/lib/owl-carousel/owl.carousel.min.js'%}"></script>
    <script src="{% static 'js/lib/owl-carousel/owl.carousel-init.js' %}"></script>
    <!-- scripit init-->
    <script src="{% static 'js/dashboard2.js'}"></script>
</body>

</html>

codigo/pcc/templates/Usuario/Editar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>AdotaPet</title>

    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">

    <!-- Styles -->
    <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body style="background-color: rgb(250, 208, 203);">

    <div class="unix-login">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="login-content">
                        <div class="login-form">
                            <div class="register-link m-t-15">
                                <a href="/accounts/meu-perfil/"><i class="ti-angle-double-left"></i></a>
                            </div>
                            <h4>Cadastro</h4>
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="id_nome">Nome </label>
                                    <input type="text" class="form-control" placeholder="{{u.first_name}}" name="first_name" maxlength="100" required id="id_first_name" value="{{u.first_name}}">
                                </div>
                                <div class="form-group">
                                    <label for="id_sobrenome">Sobrenome</label>
                                    <input class="form-control" placeholder="{{u.last_name}}"  type="text" name="last_name" maxlength="100" required id="id_last_name" value="{{u.last_name}}">
                                </div>
                                <div class="form-group">
                                    <label for="id_email">Email</label>
                                    <input class="form-control" placeholder="{{u.email}}" type="email" name="email" maxlength="256" required id="id_email" value="{{u.email}}">
                                </div>
                                <div class="form-group">
                                    <label for="id_telefone">Telefone</label>
                                    <input class="form-control" placeholder="{{u.telefone}}" type="text" name="telefone" maxlength="15" required id="id_telefone" value="{{u.telefone}}">
                                </div>
                                <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30" style="background-color: rgb(233, 110, 96);">Finalizar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

codigo/pcc/templates/Usuario/Listar.html
{% if usuarios %}
    {% for i in usuarios %}
        {{i.nome}}
        <a href="/usuario/detalhar/{{i.id}}"><button type="button">Detalhar</button></a>
    {% endfor %}
{% else %}
sem cadastros
{% endif %}