codigo/pcc/ONG/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('cadastro/', views.Cadastro, name='Cadastro'),
    path('editar/', views.Editar, name='Editar'),
    path('listar/', views.Listar, name='Listar'),
    path('detalhar/<id_ong>', views.Detalhar, name='Detalhar'),
    path('meu-perfil/', views.MeuPerfil, name='MeuPerfil')
]

codigo/pcc/animal/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('cadastro/', views.Cadastro, name='Cadastro'),
    path('editar/<int:id_animal>', views.Editar, name='Editar'),
    path('listar/', views.Listar, name='Listar'),
    path('detalhar/<int:id_animal>', views.Detalhar, name='Detalhar'),
    path('detalhar-2/<int:id_animal>', views.Detalhar2, name='Detalhar2'),
    path('deletar/<int:id_animal>', views.Deletar, name='Deletar'),
    path('adotar/<int:id_animal>', views.Adotar, name='Adotar'),
    path('', views.ListarparaONG, name='ListarparaONG')
]

codigo/pcc/pcc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('user.urls')),
    path('', include('user.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
    path('ong/', include('ONG.urls')),
    path('usuario/', include('usuario.urls')),
    path('animais/', include('animal.urls'))
]

codigo/pcc/ONG/models.py
from django.db import models
from django.contrib.auth import get_user_model
from user.models import Usuario


class ONG(models.Model):
    email = models.EmailField(max_length = 256, blank=False, null=True)
    nome = models.CharField(max_length = 100, blank=False, null=True)
    cidade = models.CharField(max_length=100, blank=False, null=True)
    UF = models.CharField(max_length=100, blank=False, null=True)
    rua = models.CharField(max_length=100, blank=False, null=True)
    numero = models.CharField(max_length=10, blank=False, null=True)
    bairro = models.CharField(max_length=100, blank=False, null=True)
    telefone = models.CharField(max_length=15, blank=False, null=True)
    imagem = models.ImageField(upload_to='static/imagens/ong/', null=True, blank=True)
    user = models.OneToOneField(Usuario, on_delete=models.CASCADE)

codigo/pcc/animal/models.py
from django.db import models
from ONG.models import ONG

class Animal(models.Model):
    nome = models.CharField(max_length = 100, blank=False, null=True)
    pelagem = models.CharField(max_length=100, blank=False, null=True)
    especie = models.CharField(max_length=100, blank=False, null=True)
    tamanho = models.CharField(max_length=100, blank=False, null=True)
    Sexo_animal = (
        ('M', 'Macho'),
        ('F', 'Fêmea')
    )
    sexo = models.CharField(max_length=10, choices=Sexo_animal)
    Status_animal = (
        ('Adotado', 'Adotado'),
        ('Nao_adotado', 'Não Adotado')
    )
    status = models.CharField(max_length=50, choices=Status_animal)
    detalhes = models.TextField(max_length=10000, blank=True, null=True)
    imagem = models.ImageField(upload_to='static/imagens/animal/', null=True, blank=False)
    ong = models.ForeignKey(ONG, on_delete=models.PROTECT, related_name='ONG')

codigo/pcc/animal/forms.py
from django import forms 
from .models import Animal

class AdicionarAnimal(forms.ModelForm):
    class Meta:
        model= Animal
        fields = ('nome', 'pelagem', 'especie', 'tamanho', 'sexo', 'status', 'detalhes', 'imagem')

codigo/pcc/animal/views.py
from django.shortcuts import render, redirect, get_object_or_404, reverse
from django.contrib.auth.decorators import login_required
from .forms import AdicionarAnimal
from .models import Animal
from ONG.models import ONG
from ONG.views import Detalhar
from user.models import Usuario
import os 

@login_required
def Cadastro (request):
    if request.method =='POST':
        form = AdicionarAnimal(request.POST, request.FILES)
        u = request.user
        ong = get_object_or_404(ONG,user=u)
        if form.is_valid():
            a = form.save(commit=False)
            a.ong = ong
            a.save()
            return redirect('/accounts/')
    else:
        form = AdicionarAnimal()
    
    return render(request, 'Animal/Cadastro.html', {'form': form})

@login_required
def Editar(request, id_animal):
    animal= get_object_or_404(Animal, pk=id_animal)
    form = AdicionarAnimal(instance=animal)
    if request.method == 'POST':
        form = AdicionarAnimal(request.POST, request.FILES, instance=animal)
        
        requisicao = request.POST.get('imagem', False)
        if requisicao:
            if len(animal.imagem)>0:
                os.remove(animal.imagem.path)
            animal.imagem = request.FILES['imagem']


        if form.is_valid():
            form.save()
            return redirect('/accounts/')
        else:
            return render(request, 'Animal/Editar.html', {'form': form, 'animal': animal})   
    
    else:
        return render(request, 'Animal/Editar.html', {'form': form, 'animal':animal})

@login_required
def Listar(request):
    #u = request.Usuario
    #usuario_atual = get_object_or_404(Usuario, user=u)
    animais = Animal.objects.filter(status = 'Nao_adotado')
    return render(request, 'Animal/Listar.html', {'animais': animais})

@login_required
def ListarparaONG(request):
    u = request.user
    o = get_object_or_404(ONG, user=u)
    animais = Animal.objects.filter(ong=o)
    return render(request, 'Animal/ListarONG.html', {'animais': animais, 'ong':o})

@login_required
def Detalhar(request, id_animal):
    animal = Animal.objects.get(pk=id_animal)
    return render(request, 'Animal/Detalhar.html', {'animal': animal})

@login_required
def Detalhar2(request, id_animal):
    animal = Animal.objects.get(pk=id_animal)
    return render(request, 'Animal/Detalhar2.html', {'animal': animal})

@login_required
def Deletar(request, id_animal):
    Animal.objects.get(pk=id_animal).delete()
    return redirect('/accounts/')

@login_required
def Adotar(request, id_animal):
    animal = Animal.objects.get(pk=id_animal)
    animal.status = 'Adotado'
    animal.save()
    return redirect('/accounts/')

codigo/pcc/templates/Animal/Cadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>Adotapet</title>

    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">

    <!-- Styles -->
    <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body style="background-color: rgb(250, 208, 203);">

    <div class="unix-login">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="login-content">
                        <div class="login-form">
                            <h4>Cadastro do animal</h4>
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="id_nome">Nome:</label>
                                    <input type="text" class="form-control" name="nome" maxlength="100" required id="id_nome">
                                </div>
                                <div class="form-group">
                                    <label for="id_pelagem">Pelagem:</label>
                                    <input type="text" class="form-control" name="pelagem" maxlength="100" required id="id_pelagem">
                                </div>
                                <div class="form-group">
                                    <label for="id_especie">Especie:</label>
                                    <input type="text"  class="form-control" name="especie" maxlength="100" required id="id_especie">
                                </div>
                                <div class="form-group">
                                    <label for="id_tamanho">Tamanho:</label>
                                    <input type="text" class="form-control" name="tamanho" maxlength="100" required id="id_tamanho">
                                </div>
                                <div class="form-group">
                                    <label for="id_sexo">Sexo</label>
                                    <select name="sexo" required id="id_sexo"  class="form-control">
                                        <option value="" selected>---------</option>    
                                        <option value="M">Macho</option>
                                        <option value="F">Fêmea</option>
                                      </select>
                                </div>
                                <div class="form-group">
                                    <label for="id_status">Status</label>
                                    <select name="status" required id="id_status"  class="form-control">
                                        <option value="" selected>---------</option>
                                        <option value="Adotado">Adotado</option>
                                        <option value="Nao_adotado">Não Adotado</option>
                                    </select>
                                </div>
                                <div class="form-group">
                                    <label for="id_detalhes">Detalhes:</label>
                                    <textarea name="detalhes" class="form-control" cols="40" rows="10" maxlength="10000"  id="id_detalhes"></textarea>
                                </div>
                                <div class="form-group">
                                    <label for="id_telefone">Selecione uma imagem de perfil</label>
                                    <input type="file" class="form-control" id="id_imagem" name="imagem" required>
                                </div>
                                <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30" style="background-color: rgb(233, 110, 96);">Cadastrar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

codigo/pcc/templates/Animal/Detalhar.html

{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=chrome">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- theme meta -->
    <meta name="theme-name" content="focus" />
    <title>AdotaPet</title>
    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">
    <!-- Styles -->
    <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/chartist/chartist.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/owl.carousel.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/lib/owl.theme.default.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/lib/menubar/sidebar.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body style="background-color: rgb(253, 237, 232);">

    <!-- /# sidebar -->

    <div class="header" style="margin-left:0px">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="float-left">
                        <div class="header-icon" >
                            <span class="user-avatar">
                                <a href="/animais/listar/" class="btn-outline btn btn-link"><i class="ti-angle-double-left"></i></a> 
                            </span>
                        </div>
                    </div>
                    <div class="float-right">
                        <div class="header-icon" >
                            <span class="user-avatar">
                                <a href="/accounts/meu-perfil/" class="btn-outline btn btn-link"><i class="ti-settings"></i></a> 
                            </span>
                            <span class="user-avatar"> 
                                <a href="/accounts/logout/" class="btn-outline btn btn-link " name='Sair'><i class="ti-shift-right"></i></a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="content-wrap">
        <div class="main">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-4 col-xl-3">
                        <div class="card">
                            <div class="card-body">
                                <div class="media align-items-center mb-4">
                                    <img class="mr-3" src="/{{animal.imagem}}" width="60" height="60" alt="">
                                </div>
                                
                            </div>
                        </div>  
                    </div>
                    <div class="col-lg-8 col-xl-9">
                        <div class="card">
                            <div class="card-body">
                                <div class="media-body">
                                    <h3 class="mb-0">{{animal.nome}}</h3>
                                </div>
                                <p>Pelagem: {{animal.pelagem}}</p>
                                <p>Espécie: {{animal.especie}}</p>
                                <p>Tamanho: {{animal.tamanho}}</p>
                                <p>Sexo: {{animal.sexo}}</p>
                                <p>Detalhes: {{animal.detalhes}}</p>
                                <a class="btn btn-secondary px-3 ml-4" href='/animais/adotar/{{animal.id}}'>Adotar</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /# row -->
            </div>
        </div>
    </div>

    <!-- jquery vendor -->
    <script src="{% static 'js/lib/jquery.min.js' %}"></script>
    <script src="{% static 'js/lib/jquery.nanoscroller.min.js' %}"></script>
    <!-- nano scroller -->
    <script src="{% static 'js/lib/menubar/sidebar.js' %}"></script>
    <script src="{% static 'js/lib/preloader/pace.min.js' %}"></script>
    <!-- sidebar -->

    <script src="{% static 'js/lib/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <!-- bootstrap -->


    <script src="{% static 'js/lib/chartist/chartist.min.js' %}"></script>
    <script src="{% static 'js/lib/sparklinechart/jquery.sparkline.min.js' %}"></script>
    <script src="{% static 'js/lib/sparklinechart/sparkline.init.js' %}"></script>
    <script src="{% static 'js/lib/owl-carousel/owl.carousel.min.js'%}"></script>
    <script src="{% static 'js/lib/owl-carousel/owl.carousel-init.js' %}"></script>
    <!-- scripit init-->
    <script src="{% static 'js/dashboard2.js'}"></script>
</body>

</html>

codigo/pcc/templates/Animal/Detalhar2.html

{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=chrome">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- theme meta -->
    <meta name="theme-name" content="focus" />
    <title>AdotaPet</title>
    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">
    <!-- Styles -->
    <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/chartist/chartist.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/owl.carousel.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/lib/owl.theme.default.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/lib/menubar/sidebar.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body style="background-color: rgb(253, 237, 232);">

    <!-- /# sidebar -->

    <div class="header" style="margin-left:0px">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="float-left">
                        <div class="header-icon" >
                            <span class="user-avatar">
                                <a href="/animais/" class="btn-outline btn btn-link"><i class="ti-angle-double-left"></i></a> 
                            </span>
                        </div>
                    </div>
                    <div class="float-right">
                        <div class="header-icon" >
                            <span class="user-avatar">
                                <a href="/ong/meu-perfil/" class="btn-outline btn btn-link"><i class="ti-settings"></i></a> 
                            </span>
                            <span class="user-avatar"> 
                                <a href="/accounts/logout/" class="btn-outline btn btn-link " name='Sair'><i class="ti-shift-right"></i></a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="content-wrap">
        <div class="main">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-4 col-xl-3">
                        <div class="card">
                            <div class="card-body">
                                <div class="media align-items-center mb-4">
                                    <img class="mr-3" src="/{{animal.imagem}}" width="60" height="60" alt="">
                                </div>
                                
                            </div>
                        </div>  
                    </div>
                    <div class="col-lg-8 col-xl-9">
                        <div class="card">
                            <div class="card-body">
                                <div class="media-body">
                                    <h3 class="mb-0">{{animal.nome}}</h3>
                                </div>
                                <p>Pelagem: {{animal.pelagem}}</p>
                                <p>Espécie: {{animal.especie}}</p>
                                <p>Tamanho: {{animal.tamanho}}</p>
                                <p>Sexo: {{animal.sexo}}</p>
                                <p>Detalhes: {{animal.detalhes}}</p>
                                <a class="btn btn-secondary px-3 ml-4" href='/animais/editar/{{animal.id}}'>Editar</a>
                                <a class="btn btn-secondary px-3 ml-4" href='/animais/deletar/{{animal.id}}'>Deletar</a>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /# row -->
            </div>
        </div>
    </div>

    <!-- jquery vendor -->
    <script src="{% static 'js/lib/jquery.min.js' %}"></script>
    <script src="{% static 'js/lib/jquery.nanoscroller.min.js' %}"></script>
    <!-- nano scroller -->
    <script src="{% static 'js/lib/menubar/sidebar.js' %}"></script>
    <script src="{% static 'js/lib/preloader/pace.min.js' %}"></script>
    <!-- sidebar -->

    <script src="{% static 'js/lib/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <!-- bootstrap -->


    <script src="{% static 'js/lib/chartist/chartist.min.js' %}"></script>
    <script src="{% static 'js/lib/sparklinechart/jquery.sparkline.min.js' %}"></script>
    <script src="{% static 'js/lib/sparklinechart/sparkline.init.js' %}"></script>
    <script src="{% static 'js/lib/owl-carousel/owl.carousel.min.js'%}"></script>
    <script src="{% static 'js/lib/owl-carousel/owl.carousel-init.js' %}"></script>
    <!-- scripit init-->
    <script src="{% static 'js/dashboard2.js'}"></script>
</body>

</html>

codigo/pcc/templates/Animal/Editar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>AdotaPet</title>

    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">

    <!-- Styles -->
    <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body style="background-color: rgb(250, 208, 203);">

    <div class="unix-login">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="login-content">
                        <div class="login-form">
                            <div class="register-link m-t-15">
                                <a href="/animais/detalhar-2/{{animal.id}}"><i class="ti-angle-double-left"></i></a>
                            </div>
                            <h4>Cadastro do animal</h4>
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="id_nome">Nome:</label>
                                    <input type="text" class="form-control" name="nome" maxlength="100" required id="id_nome" value="{{animal.nome}}">
                                </div>
                                <div class="form-group">
                                    <label for="id_pelagem">Pelagem:</label>
                                    <input type="text" class="form-control" name="pelagem" maxlength="100" required id="id_pelagem" value="{{animal.pelagem}}">
                                </div>
                                <div class="form-group">
                                    <label for="id_especie">Especie:</label>
                                    <input type="text"  class="form-control" name="especie" maxlength="100" required id="id_especie" value="{{animal.especie}}">
                                </div>
                                <div class="form-group">
                                    <label for="id_tamanho">Tamanho:</label>
                                    <input type="text" class="form-control" name="tamanho" maxlength="100" required id="id_tamanho" value="{{animal.tamanho}}">
                                </div>
                                {% if animal.sexo == "M" %}
                                <div class="form-group">
                                    <label for="id_sexo">Sexo</label>
                                    <select name="sexo" required id="id_sexo"  class="form-control">
                                        <option value="M" selected>Macho</option>
                                        <option value="F">Fêmea</option>
                                      </select>
                                </div>
                                {% else %}
                                <div class="form-group">
                                    <label for="id_sexo">Sexo</label>
                                    <select name="sexo" required id="id_sexo"  class="form-control">  
                                        <option value="M">Macho</option>
                                        <option value="F" selected>Fêmea</option>
                                      </select>
                                </div>
                                {% endif %}
                                {% if animal.status == "Adotado" %}
                                <div class="form-group">
                                    <label for="id_status">Status</label>
                                    <select name="status" required id="id_status"  class="form-control">
                                        <option value="Adotado" selected>Adotado</option>
                                        <option value="Nao_adotado">Não Adotado</option>
                                    </select>
                                </div>
                                {% else %}
                                <div class="form-group">
                                    <label for="id_status">Status</label>
                                    <select name="status" required id="id_status"  class="form-control">
                                        <option value="Adotado">Adotado</option>
                                        <option value="Nao_adotado" selected>Não Adotado</option>
                                    </select>
                                </div>
                                {% endif %}
                                <div class="form-group">
                                    <label for="id_detalhes">Detalhes:</label>
                                    <input name="detalhes" class="form-control" cols="40" rows="10" maxlength="10000" id="id_detalhes" value="{{animal.detalhes}}">
                                </div>
                                <div class="form-group">
                                    <label for="id_imagem">Selecione uma imagem:</label> <br>
                                    <label><a href="/{{animal.imagem}}">Visualizar imagem atual</a></label>
                                    <input type="file" class="form-control" id="id_imagem" name="imagem">
                                </div>
                                <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-15" style="background-color: rgb(233, 110, 96);">Finalizar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>