codigo/pcc/ONG/urls.py
from django.contrib import admin
from django.urls import path, include
from . import views

urlpatterns = [
    path('cadastro/', views.Cadastro, name='Cadastro'),
    path('editar/', views.Editar, name='Editar'),
    path('listar/', views.Listar, name='Listar'),
    path('detalhar/<id_ong>', views.Detalhar, name='Detalhar'),
    path('meu-perfil/', views.MeuPerfil, name='MeuPerfil')
]

codigo/pcc/pcc/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('user.urls')),
    path('', include('user.urls')),
    path('accounts/', include('django.contrib.auth.urls')), 
    path('ong/', include('ONG.urls')),
    path('usuario/', include('usuario.urls')),
    path('animais/', include('animal.urls'))
]

codigo/pcc/ONG/models.py
from django.db import models
from django.contrib.auth import get_user_model
from user.models import Usuario


class ONG(models.Model):
    email = models.EmailField(max_length = 256, blank=False, null=True)
    nome = models.CharField(max_length = 100, blank=False, null=True)
    cidade = models.CharField(max_length=100, blank=False, null=True)
    UF = models.CharField(max_length=100, blank=False, null=True)
    rua = models.CharField(max_length=100, blank=False, null=True)
    numero = models.CharField(max_length=10, blank=False, null=True)
    bairro = models.CharField(max_length=100, blank=False, null=True)
    telefone = models.CharField(max_length=15, blank=False, null=True)
    imagem = models.ImageField(upload_to='static/imagens/ong/', null=True, blank=True)
    user = models.OneToOneField(Usuario, on_delete=models.CASCADE)

codigo/pcc/ONG/forms.py
from django import forms 
from .models import ONG

class AdicionarONG(forms.ModelForm):
    class Meta:
        model= ONG
        fields = ('nome', 'email','telefone', 'UF', 'cidade', 'rua', 'numero', 'bairro', 'imagem')

codigo/pcc/ONG/views.py
from django.shortcuts import render, redirect, get_object_or_404
from django.contrib.auth.decorators import login_required
from .forms import AdicionarONG
from .models import ONG
import os

@login_required
def Cadastro (request):
    if request.method =='POST':
        form = AdicionarONG(request.POST, request.FILES)
        if form.is_valid():
            a = form.save(commit=False)
            a.user = request.user
            a.save()
            return redirect('/accounts/')
    else:
        form = AdicionarONG()
    
    return render(request, 'ONG/Cadastro.html', {'form': form})

@login_required
def Editar(request):
    usuario = request.user
    ong = get_object_or_404(ONG, user=usuario)
    form = AdicionarONG(instance=ong)
    if request.method == 'POST':
        form = AdicionarONG(request.POST, request.FILES, instance=ong)

        requisicao = request.POST.get('imagem', False)
        if requisicao:
            if len(ong.imagem)>0:
                os.remove(ong.imagem.path)
            ong.imagem = request.FILES['imagem']

        if form.is_valid():
            form.save()
            return redirect('/accounts/')
        else:
            return render(request, 'ONG/Editar.html', {'form': form, 'ong':ong})   
    
    else:
        return render(request, 'ONG/Editar.html', {'form': form, 'ong':ong})

@login_required
def Listar(request):
    ongs = ONG.objects.all()
    return render(request, 'ONG/Listar.html', {'ongs': ongs})

@login_required
def Detalhar(request, id_ong):
    ong = ONG.objects.get(pk=id_ong)
    return render(request, 'ONG/Detalhar.html', {'ong': ong})

@login_required
def MeuPerfil(request):
    u = request.user
    ong = ONG.objects.get(user=u)
    return render(request, 'ONG/MeuPerfil.html', {'ong': ong})

codigo/pcc/templates/ONG/Cadastro.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>AdotaPet</title>

    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">

    <!-- Styles -->
    <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body style="background-color: rgb(250, 208, 203);">

    <div class="unix-login">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="login-content">
                        <div class="login-form">
                            <h4>Cadastro</h4>
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="id_nome">Nome de usuario</label>
                                    <input type="text" class="form-control" placeholder="Nome" name="nome" maxlength="100" required id="id_nome">
                                </div>
                                <div class="form-group">
                                    <label for="id_email">Email</label>
                                    <input class="form-control" placeholder="Email" type="email" name="email" maxlength="256" required id="id_email">
                                </div>
                                <div class="form-group">
                                    <label for="id_telefone">Telefone</label>
                                    <input class="form-control" placeholder="Telefone" type="text" name="telefone" maxlength="15" required id="id_telefone">
                                </div>
                                <div class="form-group">
                                    <label for="id_UF">Estado</label>
                                    <input class="form-control" placeholder="Estado" type="text"  name="UF" maxlength="100" required id="id_UF">
                                </div>
                                <div class="form-group">
                                    <label for="id_cidade">Cidade</label>
                                    <input class="form-control" placeholder="Cidade" type="text" name="cidade" maxlength="100" required id="id_cidade">
                                </div>
                                <div class="form-group">
                                    <label for="id_rua">Rua</label>
                                    <input class="form-control" placeholder="Rua" type="text"  name="rua" maxlength="100" required id="id_rua">
                                </div>
                                <div class="form-group">
                                    <label for="id_numero">Número</label>
                                    <input class="form-control" placeholder="Numero" type="text" name="numero" maxlength="10" required id="id_numero">
                                </div>
                                <div class="form-group">
                                    <label for="id_bairro">Bairro</label>
                                    <input class="form-control" placeholder="Bairro" type="text"  name="bairro" maxlength="100" required id="id_bairro">
                                </div>
                                <div class="form-group">
                                    <label for="id_telefone">Selecione uma imagem de perfil</label>
                                    <input type="file" class="form-control" id="id_imagem" name="imagem">
                                </div>
                                <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30" style="background-color: rgb(233, 110, 96);">Cadastrar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

codigo/pcc/templates/ONG/Detalhar.html

{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- theme meta -->
    <meta name="theme-name" content="focus" />
    <title>AdotaPet</title>
    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">
    <!-- Styles -->
    <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/chartist/chartist.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/owl.carousel.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/lib/owl.theme.default.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/lib/menubar/sidebar.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body style="background-color: rgb(253, 237, 232);">

    <!-- /# sidebar -->

    <div class="header" style="margin-left:0px">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="float-left">
                        <div class="header-icon" >
                            <span class="user-avatar">
                                <a href="/ong/listar/" class="btn-outline btn btn-link"><i class="ti-angle-double-left"></i></a> 
                            </span>
                        </div>
                    </div>
                    <div class="float-right">
                        <div class="header-icon" >
                            <span class="user-avatar">
                                <a href="/accounts/meu-perfil/" class="btn-outline btn btn-link"><i class="ti-settings"></i></a> 
                            </span>
                            <span class="user-avatar"> 
                                <a href="/accounts/logout/" class="btn-outline btn btn-link " name='Sair'><i class="ti-shift-right"></i></a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="content-wrap">
        <div class="main">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-4 col-xl-3">
                        <div class="card">
                            <div class="card-body">
                                <div class="media align-items-center mb-4">
                                    <img class="mr-3" src="/{{ong.imagem}}" width="60" height="60" alt="">
                                </div>
                                
                            </div>
                        </div>  
                    </div>
                    <div class="col-lg-8 col-xl-9">
                        <div class="card">
                            <div class="card-body">
                                <div class="media-body">
                                    <h3 class="mb-0">{{ong.nome}}</h3>
                                </div> 
                                <p>Email: {{ong.email}}</p>
                                <p>Telefone: {{ong.telefone}}</p>
                                <p>Cidade: {{ong.cidade}} - {{ong.UF}}</p>
                                <p>Endereço:</p>
                                <p>Rua: {{ong.rua}}</p>
                                <p>Número: {{ong.numero}}</p>
                                <p>Bairro: {{ong.bairro}}</p>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /# row -->
            </div>
        </div>
    </div>

    <!-- jquery vendor -->
    <script src="{% static 'js/lib/jquery.min.js' %}"></script>
    <script src="{% static 'js/lib/jquery.nanoscroller.min.js' %}"></script>
    <!-- nano scroller -->
    <script src="{% static 'js/lib/menubar/sidebar.js' %}"></script>
    <script src="{% static 'js/lib/preloader/pace.min.js' %}"></script>
    <!-- sidebar -->

    <script src="{% static 'js/lib/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <!-- bootstrap -->


    <script src="{% static 'js/lib/chartist/chartist.min.js' %}"></script>
    <script src="{% static 'js/lib/sparklinechart/jquery.sparkline.min.js' %}"></script>
    <script src="{% static 'js/lib/sparklinechart/sparkline.init.js' %}"></script>
    <script src="{% static 'js/lib/owl-carousel/owl.carousel.min.js'%}"></script>
    <script src="{% static 'js/lib/owl-carousel/owl.carousel-init.js' %}"></script>
    <!-- scripit init-->
    <script src="{% static 'js/dashboard2.js'}"></script>
</body>

</html>

codigo/pcc/templates/ONG/Editar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">

    <title>AdotaPet</title>

    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">

    <!-- Styles -->
    <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body style="background-color: rgb(250, 208, 203);">

    <div class="unix-login">
        <div class="container-fluid">
            <div class="row justify-content-center">
                <div class="col-lg-6">
                    <div class="login-content">
                        <div class="login-form">
                            <div class="register-link m-t-15">
                                <a href="/ong/meu-perfil/"><i class="ti-angle-double-left"></i></a>
                            </div>
                            <h4>Cadastro</h4>
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <div class="form-group">
                                    <label for="id_nome">Nome de usuario</label>
                                    <input type="text" class="form-control" placeholder="{{ong.nome}}" name="nome" maxlength="100" required id="id_nome" value="{{ong.nome}}">
                                </div>
                                <div class="form-group">
                                    <label for="id_email">Email</label>
                                    <input class="form-control" placeholder="{{ong.email}}" type="email" name="email" maxlength="256" required id="id_email" value="{{ong.email}}">
                                </div>
                                <div class="form-group">
                                    <label for="id_telefone">Telefone</label>
                                    <input class="form-control" placeholder="{{ong.telefone}}" type="text" name="telefone" maxlength="15" required id="id_telefone" value="{{ong.telefone}}">
                                </div>
                                <div class="form-group">
                                    <label for="id_UF">Estado</label>
                                    <input class="form-control" placeholder="{{ong.UF}}" type="text"  name="UF" maxlength="100" required id="id_UF" value="{{ong.UF}}">
                                </div>
                                <div class="form-group">
                                    <label for="id_cidade">Cidade</label>
                                    <input class="form-control" placeholder="{{ong.cidade}}" type="text" name="cidade" maxlength="100" required id="id_cidade" value="{{ong.cidade}}">
                                </div>
                                <div class="form-group">
                                    <label for="id_rua">Rua</label>
                                    <input class="form-control" placeholder="{{ong.rua}}" type="text"  name="rua" maxlength="100" required id="id_rua" value="{{ong.rua}}">
                                </div>
                                <div class="form-group">
                                    <label for="id_numero">Número</label>
                                    <input class="form-control" placeholder="{{ong.numero}}" type="text" name="numero" maxlength="10" required id="id_numero" value="{{ong.numero}}">
                                </div>
                                <div class="form-group">
                                    <label for="id_bairro">Bairro</label>
                                    <input class="form-control" placeholder="{{ong.bairro}}" type="text"  name="bairro" maxlength="100" required id="id_bairro" value="{{ong.bairro}}">
                                </div>
                                <div class="form-group">
                                    <label for="id_imagem">Selecione uma imagem:</label> <br>
                                    <label><a href="/{{ong.imagem}}">Visualizar imagem atual</a></label>
                                    <input type="file" class="form-control" id="id_imagem" name="imagem">
                                </div>
                                <button type="submit" class="btn btn-primary btn-flat m-b-30 m-t-30" style="background-color: rgb(233, 110, 96);">Finalizar</button>
                            </form>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>

</body>

</html>

codigo/pcc/templates/ONG/Listar.html
{% load static %}
<!DOCTYPE html>
<html lang="en">

<head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- theme meta -->
    <meta name="theme-name" content="focus" />
    <title>AdotaPet</title>
    <!-- ================= Favicon ================== -->
    <!-- Standard -->
    <link rel="shortcut icon" href="http://placehold.it/64.png/000/fff">
    <!-- Retina iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="144x144" href="http://placehold.it/144.png/000/fff">
    <!-- Retina iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="114x114" href="http://placehold.it/114.png/000/fff">
    <!-- Standard iPad Touch Icon-->
    <link rel="apple-touch-icon" sizes="72x72" href="http://placehold.it/72.png/000/fff">
    <!-- Standard iPhone Touch Icon-->
    <link rel="apple-touch-icon" sizes="57x57" href="http://placehold.it/57.png/000/fff">
    <!-- Styles -->
    <link href="{% static 'css/lib/font-awesome.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/themify-icons.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/bootstrap.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/helper.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/chartist/chartist.min.css' %}" rel="stylesheet">
    <link href="{% static 'css/lib/owl.carousel.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/lib/owl.theme.default.min.css' %}" rel="stylesheet" />
    <link href="{% static 'css/lib/menubar/sidebar.css' %}" rel="stylesheet">
    <link href="{% static 'css/style.css' %}" rel="stylesheet">
</head>

<body style="background-color: rgb(253, 237, 232);">

    <!-- /# sidebar -->

    <div class="header" style="margin-left:0px">
        <div class="container-fluid">
            <div class="row">
                <div class="col-lg-12">
                    <div class="float-left">
                        <div class="header-icon" >
                            <span class="user-avatar">
                                <h4>AdotaPet</h4>
                            </span>
                        </div>
                    </div>
                    <div class="float-right">
                        <div class="header-icon" >
                            <span class="user-avatar">
                                <a href="/accounts/meu-perfil/" class="btn-outline btn btn-link"><i class="ti-settings"></i></a> 
                            </span>
                            <span class="user-avatar"> 
                                <a href="/accounts/logout/" class="btn-outline btn btn-link " name='Sair'><i class="ti-shift-right"></i></a>
                            </span>
                        </div>
                    </div>
                </div>
            </div>
        </div>
    </div>


    <div class="content-wrap">
        <div class="main">
            <div class="container-fluid">
                <div class="row">
                    <div class="col-lg-8 p-r-0 title-margin-right">
                        <div class="page-header">
                            <div class="page-title">
                            </div>
                        </div>
                    </div>
                    <div class="col-lg-4 p-l-0 title-margin-left">
                        <div class="page-header">
                            <div class="page-title">
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="/animais/listar/">Animais</a></li>
                                </ol>
                                <ol class="breadcrumb">
                                    <li class="breadcrumb-item"><a href="/ong/listar/">ONG</a></li>
                                </ol>
                            </div>
                        </div>
                    </div>
                </div>
                <!-- /# row -->
                <section id="main-content">
                    <div class="row">
                        {% if ongs %}
                            {% for i in ongs %}
                            <div class="col-lg-4">
                                <div class="card">
                                    <div class="stat-widget-one">
                                        <div class="stat-icon dib"><img class="mr-3" src="/{{i.imagem}}" width="60" height="60" alt="">
                                        </div>
                                        <div class="stat-content dib">
                                            <div class="card-title"><h4>{{i.nome}}</h4></div>
                                            <a href="/ong/detalhar/{{i.id}}"><button type="button" class="btn btn-default btn-sm btn-outline m-b-10">Detalhar</button></a>
                                        </div>
                                    </div>
                                </div>
                            </div>
                            {% endfor %}
                        {% endif %}
                        
                    </div>
                    </div>
                </section>
            </div>
        </div>
    </div>

    <!-- jquery vendor -->
    <script src="{% static 'js/lib/jquery.min.js' %}"></script>
    <script src="{% static 'js/lib/jquery.nanoscroller.min.js' %}"></script>
    <!-- nano scroller -->
    <script src="{% static 'js/lib/menubar/sidebar.js' %}"></script>
    <script src="{% static 'js/lib/preloader/pace.min.js' %}"></script>
    <!-- sidebar -->

    <script src="{% static 'js/lib/bootstrap.min.js' %}"></script>
    <script src="{% static 'js/scripts.js' %}"></script>
    <!-- bootstrap -->


    <script src="{% static 'js/lib/chartist/chartist.min.js' %}"></script>
    <script src="{% static 'js/lib/sparklinechart/jquery.sparkline.min.js' %}"></script>
    <script src="{% static 'js/lib/sparklinechart/sparkline.init.js' %}"></script>
    <script src="{% static 'js/lib/owl-carousel/owl.carousel.min.js'%}"></script>
    <script src="{% static 'js/lib/owl-carousel/owl.carousel-init.js' %}"></script>
    <!-- scripit init-->
    <script src="{% static 'js/dashboard2.js'}"></script>
</body>

</html>


